version: '3'
services:
  db:
    image: postgres:10
    container_name: db_container
    volumes:
      - ./database/db:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/project
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - 'db:db'
